image: node:18

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - Get-Location
    - Get-ChildItem
    - cd employee_frontend
    - Get-ChildItem
    - npm install
    - $env:CI = "false"; npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 week
  only:
    - main
    - develop
    - merge_requests

test:
  stage: test
  script:
    - cd employee_frontend
    - npm install
    - npm test -- --passWithNoTests
  only:
    - main
    - develop
    - merge_requests

cypress-e2e:
  stage: test
  image: cypress/included:12.17.4
  services:
    - name: cypress/browsers:node18.12.0-chrome107-ff107
      alias: browsers
  variables:
    CYPRESS_baseUrl: "http://localhost:3001"
  script:
    - cd employee_frontend
    - npm install
    - npm run start &
    - npx wait-on http://localhost:3001
    - npx cypress run --browser chrome
  only:
    - main
    - develop
    - merge_requests

e2e-integration:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
  script:
    - docker pull registry.gitlab.com/i459452/LibraFlow_Book_Server:latest
    - docker pull registry.gitlab.com/i459452/LibraFlow_BookUnit_Server:latest
    - docker pull registry.gitlab.com/i459452/LibraFlow_User_Server:latest
    - docker pull registry.gitlab.com/i459452/LibraFlow_Borrowing_Server:latest
    - docker pull registry.gitlab.com/i459452/LibraFlow_API_Gateway:latest
    - docker-compose -f docker-compose.e2e.yml up -d
    - npx wait-on http://localhost:3001
    - npx cypress run
  only:
    - main
    - develop
    - merge_requests