image: node:18

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - Get-Location
    - Get-ChildItem
    - cd employee_frontend
    - Get-ChildItem
    - npm install
    - $env:CI = "false"; npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 week
  only:
    - main
    - develop
    - merge_requests

test:
  stage: test
  script:
    - cd employee_frontend
    - npm install
    - npm test -- --passWithNoTests
  only:
    - main
    - develop
    - merge_requests

e2e-integration:
  stage: test
  image: node:18
  before_script:
    # Check if Docker is running (Windows-specific)
    - if (!(Test-Path "//./pipe/docker_engine")) { throw "Docker Desktop is not running. Please start Docker Desktop and try again." }
  script:
    - docker-compose -f docker-compose.e2e.yml up -d
    - npx wait-on http://localhost:3001
    - npx cypress run
  only:
    - main
    - develop
    - merge_requests