image: node:18-alpine

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 week
  only:
    - main
    - develop
    - merge_requests

test:
  stage: test
  script:
    - npm ci
    - npm test
  only:
    - main
    - develop
    - merge_requests

deploy:
  stage: deploy
  script:
    - echo "Deploying to production"
    # Add your deployment commands here
    # For example, if using AWS S3:
    # - aws s3 sync build/ s3://your-bucket-name/
  only:
    - main
  when: manual
