image: node:18

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - Get-Location
    - Get-ChildItem
    - cd employee_frontend
    - Get-ChildItem
    - npm install
    - $env:CI = "false"; npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 week
  only:
    - main
    - develop
    - merge_requests

test:
  stage: test
  script:
    - cd employee_frontend
    - npm install
    - npm test -- --passWithNoTests
  only:
    - main
    - develop
    - merge_requests

e2e-integration:
  stage: test
  image: cypress/included:12.17.4
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  before_script:
    - apk add --no-cache docker-compose
    - docker info
    - docker-compose -f docker-compose.e2e.yml up -d --build
    - npx wait-on http://localhost:3001
  script:
    - cd employee_frontend
    - npx cypress run
  after_script:
    - docker-compose -f docker-compose.e2e.yml down
  only:
    - main
    - develop
    - merge_requests