image: node:18

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - cd employee_frontend
    - npm install
    - $env:CI = "false"; npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 week
  only:
    - main
    - develop
    - merge_requests

test:
  stage: test
  script:
    - cd employee_frontend
    - npm install
    - npm test -- --passWithNoTests
  only:
    - main
    - develop
    - merge_requests

e2e-integration:
  stage: test
  script:
    # Start all services for E2E (ensure docker-compose is in PATH)
    - docker-compose -f docker-compose.e2e.yml up -d --build
    # Wait for frontend to be up (use PowerShell's curl)
    - |
      $maxAttempts = 30
      $attempt = 0
      while ($attempt -lt $maxAttempts) {
        $attempt++
        try {
          $response = Invoke-WebRequest -Uri "http://localhost:3001" -UseBasicParsing -TimeoutSec 2
          if ($response.StatusCode -eq 200) { break }
        } catch { }
        Start-Sleep -Seconds 5
      }
    - cd employee_frontend
    - npx cypress run
  after_script:
    - docker-compose -f docker-compose.e2e.yml down
  only:
    - main
    - develop
    - merge_requests