version: '3.8'
services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.5
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  book-server:
    image: book_server:latest
    ports:
      - "8081:8081"
    depends_on:
      - kafka

  bookunit-server:
    image: bookunit_server:latest
    ports:
      - "8082:8082"
    depends_on:
      - kafka

  user-server:
    image: user_server:latest
    ports:
      - "8083:8083"
    depends_on:
      - kafka

  borrowing-server:
    image: borrowing_server:latest
    ports:
      - "8084:8084"
    depends_on:
      - kafka

  api-gateway:
    image: api_gateway:latest
    ports:
      - "3000:3000"
    depends_on:
      - book-server
      - bookunit-server
      - user-server
      - borrowing-server
      - kafka

#  employee-frontend:
#    build: ./employee_frontend
#    ports:
#      - "3001:3001"
#    depends_on:
#      - api-gateway
