version: '3.8'
services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.5
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  db3:
    image: postgres:latest
    environment:
      POSTGRES_USER: user3
      POSTGRES_PASSWORD: password3
      POSTGRES_DB: db3
    ports:
      - "5434:5432"
    volumes:
      - db3-data:/var/lib/postgresql/data

  db4:
    image: postgres:latest
    environment:
      POSTGRES_USER: user4
      POSTGRES_PASSWORD: password4
      POSTGRES_DB: db4
    ports:
      - "5435:5432"
    volumes:
      - db4-data:/var/lib/postgresql/data

  db5:
    image: postgres:latest
    environment:
      POSTGRES_USER: user5
      POSTGRES_PASSWORD: password5
      POSTGRES_DB: db5
    ports:
      - "5436:5432"
    volumes:
      - db5-data:/var/lib/postgresql/data

  book-service:
    image: starcraftfan/book-service:latest
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db3:5432/db3
      - SPRING_DATASOURCE_USERNAME=user3
      - SPRING_DATASOURCE_PASSWORD=password3
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - db3

  bookunit-service:
    image: starcraftfan/bookunit-service:latest
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db4:5432/db4
      - SPRING_DATASOURCE_USERNAME=user4
      - SPRING_DATASOURCE_PASSWORD=password4
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - db4

  borrowing-service:
    image: starcraftfan/borrowing-service:latest
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db5:5432/db5
      - SPRING_DATASOURCE_USERNAME=user5
      - SPRING_DATASOURCE_PASSWORD=password5
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - db5

  user-service:
    image: starcraftfan/user-service:latest
    ports:
      - "8087:8087"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db5:5432/db5
      - SPRING_DATASOURCE_USERNAME=user5
      - SPRING_DATASOURCE_PASSWORD=password5
      - JWT_SECRET=12345678901234567890123456789012
      - KEYPART_ONE=wRJoqINwixKE9UwbjAO+wg==
      - KEYPART_TWO=/c2hupbW+7wgghMUKqg7mg==
      - ENCRYPTION_KEY=5WvoJZzv2iJDZo2Asn+VYib2+2WLrnLGpLZSJXs2EmA=
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - db5

  api-gateway:
    image: starcraftfan/api-gateway:latest
    ports:
      - "3000:3000"
    depends_on:
      - book-service
      - bookunit-service
      - borrowing-service
      - user-service

  employee-frontend:
    build:
      context: ./employee_frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    depends_on:
      - api-gateway

volumes:
  db3-data:
  db4-data:
  db5-data:
